[package]
name = "fluid_codegen"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[dependencies]
# Codegen
llvm-sys = "110"

# Language Items
fluid_parser = { path = "../fluid_parser/" }
fluid_error = { path = "../fluid_error/" }
fluid_mangle = { path = "../fluid_mangle/" }

# Panic Backtrace
backtrace = "0.3.56"
